#ifndef QPSX_GTE_RTPT_LAYOUT_H
#define QPSX_GTE_RTPT_LAYOUT_H

/*
 * The opt-in RTPT leaf is written in MIPS assembly and addresses psxRegs
 * directly. Keep its ABI constants in a header shared by the assembler and
 * the host layout audit; never duplicate these numbers in the .S file.
 */
#define QPSX_RTPT_OFF_CP2D 264
#define QPSX_RTPT_OFF_CP2C 392

#define QPSX_RTPT_OFF_SZ0  (QPSX_RTPT_OFF_CP2D + 16*4)
#define QPSX_RTPT_OFF_SZ1  (QPSX_RTPT_OFF_CP2D + 17*4)
#define QPSX_RTPT_OFF_SZ2  (QPSX_RTPT_OFF_CP2D + 18*4)
#define QPSX_RTPT_OFF_SZ3  (QPSX_RTPT_OFF_CP2D + 19*4)
#define QPSX_RTPT_OFF_IR0  (QPSX_RTPT_OFF_CP2D + 8*4)
#define QPSX_RTPT_OFF_IR1  (QPSX_RTPT_OFF_CP2D + 9*4)
#define QPSX_RTPT_OFF_IR2  (QPSX_RTPT_OFF_CP2D + 10*4)
#define QPSX_RTPT_OFF_IR3  (QPSX_RTPT_OFF_CP2D + 11*4)
#define QPSX_RTPT_OFF_SXY0 (QPSX_RTPT_OFF_CP2D + 12*4)
#define QPSX_RTPT_OFF_SXY1 (QPSX_RTPT_OFF_CP2D + 13*4)
#define QPSX_RTPT_OFF_SXY2 (QPSX_RTPT_OFF_CP2D + 14*4)
#define QPSX_RTPT_OFF_MAC0 (QPSX_RTPT_OFF_CP2D + 24*4)
#define QPSX_RTPT_OFF_MAC1 (QPSX_RTPT_OFF_CP2D + 25*4)
#define QPSX_RTPT_OFF_MAC2 (QPSX_RTPT_OFF_CP2D + 26*4)
#define QPSX_RTPT_OFF_MAC3 (QPSX_RTPT_OFF_CP2D + 27*4)

#define QPSX_RTPT_OFF_R11  (QPSX_RTPT_OFF_CP2C + 0*4)
#define QPSX_RTPT_OFF_R12  (QPSX_RTPT_OFF_CP2C + 0*4 + 2)
#define QPSX_RTPT_OFF_R13  (QPSX_RTPT_OFF_CP2C + 1*4)
#define QPSX_RTPT_OFF_R21  (QPSX_RTPT_OFF_CP2C + 1*4 + 2)
#define QPSX_RTPT_OFF_R22  (QPSX_RTPT_OFF_CP2C + 2*4)
#define QPSX_RTPT_OFF_R23  (QPSX_RTPT_OFF_CP2C + 2*4 + 2)
#define QPSX_RTPT_OFF_R31  (QPSX_RTPT_OFF_CP2C + 3*4)
#define QPSX_RTPT_OFF_R32  (QPSX_RTPT_OFF_CP2C + 3*4 + 2)
#define QPSX_RTPT_OFF_R33  (QPSX_RTPT_OFF_CP2C + 4*4)
#define QPSX_RTPT_OFF_TRX  (QPSX_RTPT_OFF_CP2C + 5*4)
#define QPSX_RTPT_OFF_TRY  (QPSX_RTPT_OFF_CP2C + 6*4)
#define QPSX_RTPT_OFF_TRZ  (QPSX_RTPT_OFF_CP2C + 7*4)
#define QPSX_RTPT_OFF_OFX  (QPSX_RTPT_OFF_CP2C + 24*4)
#define QPSX_RTPT_OFF_OFY  (QPSX_RTPT_OFF_CP2C + 25*4)
#define QPSX_RTPT_OFF_H    (QPSX_RTPT_OFF_CP2C + 26*4)
#define QPSX_RTPT_OFF_DQA  (QPSX_RTPT_OFF_CP2C + 27*4)
#define QPSX_RTPT_OFF_DQB  (QPSX_RTPT_OFF_CP2C + 28*4)
#define QPSX_RTPT_OFF_FLAG (QPSX_RTPT_OFF_CP2C + 31*4)

#endif /* QPSX_GTE_RTPT_LAYOUT_H */
